
import json
import os

# Markdown Template
MD_TEMPLATE = """# {{METADATA.name}} `{{METADATA.version}}`

> **Protocol**: {{METADATA.protocol}} | **ID**: `{{METADATA.id}}`  
> **Tools**: {{METADATA.tools}} | **Verified On**: {{METADATA.verified_on}}

{{METADATA.description}}

---

## 1. System Identity

**System Prompt**:
```text
{{SYSTEM_PROMPT}}
```

## 2. Logic Blueprints

The following logic flow allows GitHub to render the Mermaid graph natively.

<!-- BLUEPRINTS_LOOP_START -->
### Blueprint: `{{BP.name}}`

```mermaid
{{BP.graph}}
```
<!-- BLUEPRINTS_LOOP_END -->

## 3. Capabilities (Functions)

| Function Name | First Step (Preview) |
| :--- | :--- |
<!-- FUNCTIONS_LOOP_START -->| `{{FN.name}}` | `{{FN.step1}}` |
<!-- FUNCTIONS_LOOP_END -->

---
*Generated by AISOP MD Generator*
"""

def generate_md(json_path):
    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    # Detect format (Legacy vs Array)
    if isinstance(data, list):
        # Chat-Native
        system_msg = next((m for m in data if m['role'] == 'system'), {})
        user_msg = next((m for m in data if m['role'] == 'user'), {})
        
        meta = system_msg.get('content', {})
        sys_prompt = meta.get('system_prompt', '')
        
        user_content = user_msg.get('content', {})
        blueprints = user_content.get('blueprints', {})
        functions = user_content.get('functions', {})
    else:
        # Legacy
        meta = data.get('aisop', {})
        sys_prompt = meta.get('system_prompt', '')
        blueprints = data.get('blueprints', {})
        functions = data.get('functions', {})

    md = MD_TEMPLATE
    
    # 1. Metadata
    md = md.replace('{{METADATA.name}}', str(meta.get('name', 'Untitled')))
    md = md.replace('{{METADATA.id}}', str(meta.get('id', '-')))
    md = md.replace('{{METADATA.version}}', str(meta.get('version', '0.0.0')))
    md = md.replace('{{METADATA.protocol}}', str(meta.get('protocol', 'AISOP V3.1')))
    md = md.replace('{{METADATA.description}}', str(meta.get('description', '')))
    
    tools = ', '.join([f"`{t}`" for t in meta.get('tools', [])])
    verified = ', '.join([f"`{v}`" for v in meta.get('verified_on', [])])
    
    md = md.replace('{{METADATA.tools}}', tools)
    md = md.replace('{{METADATA.verified_on}}', verified)
    md = md.replace('{{SYSTEM_PROMPT}}', str(sys_prompt))

    # 2. Blueprints
    bp_start = "<!-- BLUEPRINTS_LOOP_START -->"
    bp_end = "<!-- BLUEPRINTS_LOOP_END -->"
    
    if bp_start in md and bp_end in md:
        s_idx = md.find(bp_start)
        e_idx = md.find(bp_end)
        template_part = md[s_idx + len(bp_start):e_idx]
        
        new_content = ""
        for name, graph in blueprints.items():
            item = template_part.replace('{{BP.name}}', name).replace('{{BP.graph}}', graph)
            new_content += item
        md = md[:s_idx] + new_content + md[e_idx + len(bp_end):]

    # 3. Functions
    fn_start = "<!-- FUNCTIONS_LOOP_START -->"
    fn_end = "<!-- FUNCTIONS_LOOP_END -->"
    
    if fn_start in md and fn_end in md:
        s_idx = md.find(fn_start)
        e_idx = md.find(fn_end)
        template_part = md[s_idx + len(fn_start):e_idx]
        
        new_content = ""
        for fname, fbody in functions.items():
            if not isinstance(fbody, dict): continue
            step1 = fbody.get('step1', '')
            if isinstance(step1, dict): step1 = str(step1)
            # Escape pipes for markdown table
            step1 = str(step1).replace('|', '\|').replace('\n', ' ')
            if len(step1) > 60: step1 = step1[:57] + "..."
            
            item = template_part.replace('{{FN.name}}', fname).replace('{{FN.step1}}', step1)
            new_content += item
        md = md[:s_idx] + new_content + md[e_idx + len(fn_end):]

    out_path = json_path.replace('.json', '.md')
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write(md)
    print(f"Generated {out_path}")

target_dir = r"D:\vscode\openmind\aisop\examples"
print(f"Scanning {target_dir}...")
for f in os.listdir(target_dir):
    if f.endswith('.aisop.json'):
        try:
             generate_md(os.path.join(target_dir, f))
        except Exception as e:
            print(f"Failed to generate for {f}: {e}")
